### ISSUE TITLE
BulkInsert has a limit 1 in the statement, which prevents inserting multiple records

### ISSUE THREAD

**Issue by JacobBrejnbjerg** [videokojot/EFCore.BulkExtensions.MIT#109] opened 2024-03-21 22:47 UTC
When using the following code:

using (var transaction = _ingestionDbContext.Database.BeginTransaction())
                    {
                        var bc = new BulkConfig
                        {
                            SetOutputIdentity = true,
                            PreserveInsertOrder = true,
                            PropertiesToIncludeOnUpdate = new List<string> { "" } <---- This causes the error
                        };

                        // Bulk insert into database
                        await _ingestionDbContext.BulkInsertAsync(datapointsForGroup, bc);
                            
                        await transaction.CommitAsync();
                    }

It generates the below SQL which contains LIMIT 1 preventing more than 1 record to be inserted. This is due to the PropertiesToIncludeOnUpdate containing an empty string in the array because I want to Insert and not Upsert.

INSERT INTO "table" ("Column1", "Column2" ) (SELECT "Column1", "Column2" FROM "tableTemp9398586c") **LIMIT 1** ON CONFLICT ("Id") DO NOTHING RETURNING "Id", "Column1", "Column2"

I have found it to be this line: https://github.com/videokojot/EFCore.BulkExtensions.MIT/blob/e0f0d89ab0365948cf4a371e9a9ab89a1ef37def/EFCore.BulkExtensions/SqlAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs#L97

**Comment by videokojot** [comment] 2024-03-23 14:44
Fixed by #111 . But be careful - see #110

**Comment by JacobBrejnbjerg** [comment] 2024-03-23 14:47
> Fixed by #111 . But be careful - see #110

Thank you very much. I only use BulkInsertAsync, so #110 would not be a problem for me, correct?

**Comment by videokojot** [comment] 2024-03-23 14:52
It should not, in case you are using explicit ID inserts only (ie.: not inserting with the 0 id - not relying on the autoincrement feature). But I think the problem is general - that the sequence for generating the ids is out of sync with the actual values in the table, the #110 still needs better investigation.

Or in case you are using some different mechanism for the ids (Guids)

**Closed** 2024-03-23 14:52 UTC

**Comment by videokojot** [comment] 2024-03-23 14:59
Version 16.1 with fix is released:
https://www.nuget.org/packages/EFCore.BulkExtensions.MIT/
